v>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>v
> rstack.....v >.p..v        >  p   >OO   d    v  >Smpv v
^ S     p<<<<<   A     CCC   , K   O^  O  bM  p<  p  lR v
^  SSS     T    A A   C      SK    O   O  y MM v  .Qpu< v
^     S    T   rcomp..C.>    ^ K   O   O  v    v  S     v
^ SSSS  >  T  A^    <  CCC   K   K  OOO   >    >  ^     v
^<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
